import numpy as np
NR = int(input("enter the number of rows:"))
NC = int(input("enter the number of columns:"))
print("enter the entries in a single line (seperated by space):")
entries = list(map(int, input().split()))
A = np.array(entries).reshape(NR,NC)
print("matrix X is as follows:", '\n',A)
A_inverse = np.linalg.inv(A)
transpose_of_A_inverse = np.transpose(A_inverse) 
determinant_of_A = np.linalg.det(A)
cofactor_of_A = np.dot(transpose_of_A_inverse,determinant_of_A)
print("the cofactor of a matrix is:",'\n',cofactor_of_A)
print("the determinant of a matrix is:",'\n',determinant_of_A)
adjoint_of_A = np.transpose(cofactor_of_A)
print("the adjoint of a matrix is:",'\n',adjoint_of_A)
print("the inverse of a matrix is:",'\n',A_inverse)